<?php if ($this->isTrackingEnabled()): ?>
<!-- Google Code for Purchase Conversion Page -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = "<?php echo $this->getConversionId() ?>";
    var google_conversion_language = "<?php echo $this->getLanguage() ?>";
    var google_conversion_format = "<?php echo $this->getFormat() ?>";
    var google_conversion_color = "<?php echo $this->getColor() ?>";
    var google_conversion_label = "<?php echo $this->getLabel() ?>";
    var google_conversion_value = <?php echo $this->getOrderTotal() ?>;
    var google_remarketing_only = <?php echo $this->getRemarketingOnly() ?>;
    /* ]]> */
</script>
<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js" />
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/<?php echo $this->getConversionId() ?>/?value=<?php echo $this->getOrderTotal() ?>&amp;label=<?php echo $this->getConversionLabel() ?>&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>
<?php endif; ?>
